"""report_index.json as the pages read it: what was measured, and how each thing is named."""

from __future__ import annotations

import json
import os
from collections import defaultdict
from functools import cache
from pathlib import Path

from loguru import logger

from ttnn_accuracy.ops.plan import describe, params_desc
from ttnn_accuracy.paths import CHARTS_DIR, INDEX_FILE, REPO_ROOT, REPORTS_DIR

ARCHS = ["wh", "bh"]
DTYPES = ["bf16", "fp32"]

ARCH_DISPLAY = {"wh": "Wormhole (WH)", "bh": "Blackhole (BH)"}
DTYPE_DISPLAY = {"bf16": "bfloat16", "fp32": "float32"}

# No timestamp: it was over half of a nightly's diff. Provenance lives in `_runs`.
GENERATED_NOTE = (
    "_This page is auto-generated by `ttnn-accuracy report`. Do not edit manually._\n\n"
)


@cache
def _get_index() -> dict:
    return json.loads(INDEX_FILE.read_text()) if INDEX_FILE.exists() else {}


def get_op_category(op_key: str) -> str:
    e = describe(op_key)
    return e.category if e else "unknown"


def load_summary(arch: str, dtype: str, op_key: str, variant: str) -> dict | None:
    """Load summary stats from report_index.json."""
    stats = _get_index().get(arch, {}).get(dtype, {}).get(op_key, {}).get(variant)
    return dict(stats) if stats else None


def discover_ops(categories: list[str] | None = None) -> dict:
    """arch -> dtype -> op_key -> [variants], from reports/charts/ so no local data/ is needed."""
    result: dict = {}
    if not CHARTS_DIR.exists():
        return result
    for arch_dir in sorted(CHARTS_DIR.iterdir()):
        if not arch_dir.is_dir():
            continue
        arch = arch_dir.name
        result[arch] = {}
        for dtype_dir in sorted(arch_dir.iterdir()):
            if not dtype_dir.is_dir():
                continue
            dtype = dtype_dir.name
            result[arch][dtype] = {}
            for op_key, variants_dict in sorted(_get_index().get(arch, {}).get(dtype, {}).items()):
                if not describe(op_key):
                    logger.warning("{} is measured but the manifest does not define it", op_key)
                    continue
                if categories and get_op_category(op_key) not in categories:
                    continue
                existing = [
                    v
                    for v in sorted(variants_dict.keys())
                    if (dtype_dir / f"{op_key}_{v}_ulp.svg").exists()
                ]
                if existing:
                    result[arch][dtype][op_key] = existing
    return result


def group_by_display(ops: dict[str, list[str]]) -> dict[str, list[tuple[str, str]]]:
    """{op_key: [(op_key, variant), ...]} with variants sorted by params_desc."""
    groups: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for op_key, variants in ops.items():
        for v in variants:
            groups[op_key].append((op_key, v))
    return {
        d: sorted(entries, key=lambda e: params_desc(e[0], e[1]))
        for d, entries in sorted(groups.items())
    }


def chart_rel_path(arch: str, dtype: str, op_key: str, variant: str, from_dir: Path) -> str:
    """Link from a page back to its chart. discover_ops only yields variants whose SVG exists."""
    chart = CHARTS_DIR / arch / dtype / f"{op_key}_{variant}_ulp.svg"
    up = len(from_dir.relative_to(REPORTS_DIR).parts)
    return str(Path("/".join([".."] * up)) / chart.relative_to(REPORTS_DIR))


def write(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    logger.info("wrote {}", os.path.relpath(path, REPO_ROOT))  # relative_to raises off-tree


def _usable_text(summary: dict) -> str:
    """`—` reads as a gap in the measurement, which it never is: say which case it is."""
    bound = summary.get("usable_to")
    return "nowhere" if bound == "—" else bound or "—"


def _us(perf: dict | None) -> str:
    """Microseconds, plus the spread when charts flagged the row as not worth trusting."""
    if not perf:
        return "—"
    spread = perf.get("spread_pct")
    return f"{perf['us_median']:.0f}" + (f" ±{spread:.0f}%" if spread else "")
