"""Render the reports/ markdown tree from report_index.json and reports/charts/.

Source of truth for what pages exist: reports/charts/{arch}/{dtype}/*.svg
Source of truth for summary stats:    report_index.json

An op's variants (exp default and fast_approx) share one page, one section per
parameter set.
"""

from __future__ import annotations

import json
from collections import defaultdict
from datetime import datetime
from functools import cache
from pathlib import Path

from loguru import logger

from ttnn_accuracy.measure.metrics import MIN_NORMAL
from ttnn_accuracy.measure.sweeps import SAMPLED
from ttnn_accuracy.ops.manifest import load as load_manifest
from ttnn_accuracy.ops.plan import describe, params_desc
from ttnn_accuracy.paths import CHARTS_DIR, INDEX_FILE, REPO_ROOT, REPORTS_DIR
from ttnn_accuracy.report.charts import RUNS_KEY

ARCHS = ["wh", "bh"]
DTYPES = ["bf16", "fp32"]

ARCH_DISPLAY = {"wh": "Wormhole (WH)", "bh": "Blackhole (BH)"}
DTYPE_DISPLAY = {"bf16": "bfloat16", "fp32": "float32"}

GENERATED_NOTE = (
    "_This page is auto-generated by `ttnn-accuracy report`. Do not edit manually._\n\n"
    f"_Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}_\n\n"
)


@cache
def _get_index() -> dict:
    return json.loads(INDEX_FILE.read_text()) if INDEX_FILE.exists() else {}


def get_op_category(op_key: str) -> str:
    e = describe(op_key)
    return e.category if e else "unknown"


def load_summary(arch: str, dtype: str, op_key: str, variant: str) -> dict | None:
    """Load summary stats from report_index.json."""
    stats = _get_index().get(arch, {}).get(dtype, {}).get(op_key, {}).get(variant)
    return dict(stats) if stats else None


def _input_range_text(op_key: str, dtype: str) -> str:
    """The range this op was measured over. Derived bounds differ per dtype."""
    e = describe(op_key)
    if not e or not e.bounds:
        return "unknown"
    lo, hi = e.bounds[dtype]

    def _s(v: float) -> str:
        if abs(v) <= MIN_NORMAL * 2:
            return "0" if v == 0 else (r"min\_normal" if v > 0 else r"\-min\_normal")
        return f"{v:.4g}"

    match lo == float("-inf"), hi == float("inf"):
        case True, True:
            return "all normal values"
        case True, False:
            return f"x ≤ {_s(hi)}"
        case False, True:
            return f"x ≥ {_s(lo)}"
        case _:
            return f"x ∈ [{_s(lo)}, {_s(hi)}]"


def discover_ops(categories: list[str] | None = None) -> dict:
    """Return nested dict: arch -> dtype -> op_key -> [variant_names].

    Inventory comes from reports/charts/, so this works without a local data/.
    """
    result: dict = {}
    if not CHARTS_DIR.exists():
        return result
    for arch_dir in sorted(CHARTS_DIR.iterdir()):
        if not arch_dir.is_dir():
            continue
        arch = arch_dir.name
        result[arch] = {}
        for dtype_dir in sorted(arch_dir.iterdir()):
            if not dtype_dir.is_dir():
                continue
            dtype = dtype_dir.name
            result[arch][dtype] = {}
            for op_key, variants_dict in sorted(_get_index().get(arch, {}).get(dtype, {}).items()):
                if not describe(op_key):
                    logger.warning("{} is measured but the manifest does not define it", op_key)
                    continue
                if categories and get_op_category(op_key) not in categories:
                    continue
                existing = [
                    v
                    for v in sorted(variants_dict.keys())
                    if (dtype_dir / f"{op_key}_{v}_ulp.svg").exists()
                ]
                if existing:
                    result[arch][dtype][op_key] = existing
    return result


def group_by_display(ops: dict[str, list[str]]) -> dict[str, list[tuple[str, str]]]:
    """{op_key: [(op_key, variant), ...]} with variants sorted by params_desc."""
    groups: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for op_key, variants in ops.items():
        for v in variants:
            groups[op_key].append((op_key, v))
    return {
        d: sorted(entries, key=lambda e: params_desc(e[0], e[1]))
        for d, entries in sorted(groups.items())
    }


def chart_rel_path(arch: str, dtype: str, op_key: str, variant: str, from_dir: Path) -> str:
    """Link from a page back to its chart. discover_ops only yields variants whose SVG exists."""
    chart = CHARTS_DIR / arch / dtype / f"{op_key}_{variant}_ulp.svg"
    up = len(from_dir.relative_to(REPORTS_DIR).parts)
    return str(Path("/".join([".."] * up)) / chart.relative_to(REPORTS_DIR))


def write(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    logger.info("wrote {}", path.relative_to(REPO_ROOT))


def _unmeasured_table(arch: str, dtype: str) -> str:
    """Ops in scope that produced no data here, and why.

    An op the device refuses, one that segfaults the host, one whose sweep raises — each
    is a finding, and the severest kind. Recorded only in the manifest and the run stamp,
    they would be absent from the report, which reads as ops nobody thought to measure.
    """
    rows = {
        q.rsplit(".", 1)[-1]: why for q, why in load_manifest()["rejected"].get(arch, {}).items()
    }
    rows |= _get_index().get(RUNS_KEY, {}).get(arch, {}).get(dtype, {}).get("failed", {})
    if not rows:
        return ""
    body = "".join(f"| `{op}` | {why} |\n" for op, why in sorted(rows.items()))
    return (
        f"## Not measurable on {ARCH_DISPLAY.get(arch, arch)}, "
        f"{DTYPE_DISPLAY.get(dtype, dtype)}\n\nIn scope, but produced no data — each with "
        f"the reason recorded when it was probed or swept.\n\n"
        f"| Op | Why |\n|----|-----|\n{body}\n"
    )


def _usable_text(summary: dict) -> str:
    """`—` reads as a gap in the measurement, which it never is: say which case it is."""
    return summary.get("usable_to") or "—" if summary.get("usable_to") != "—" else "nowhere"


def _specials_table(arch: str, dtype: str, entries: list[tuple[str, str]]) -> str:
    """Raw outputs at ±0, ±inf, NaN and the smallest normals, device beside golden.

    No ULP exists at these points, so agreement is shown as equality of the printed
    values — which is the question a user of the op actually has there.
    """
    rows = []
    for op_key, variant in entries:
        summary = load_summary(arch, dtype, op_key, variant)
        for r in (summary or {}).get("specials", []):
            mark = "agree" if r["y"] == r["y_ref"] else "**differ**"
            rows.append(
                f"| `{params_desc(op_key, variant)}` | {r['x']} | {r['y']} | {r['y_ref']} | {mark} |\n"
            )
    if not rows:
        return ""
    return (
        "### Special values\n\n"
        "| Variant | x | device | golden | |\n|---|---|---|---|---|\n" + "".join(rows) + "\n"
    )


def _outcome_table(arch: str, dtype: str, entries: list[tuple[str, str]]) -> str:
    """What each measured point demonstrated. Only `exact` and `inexact` carry a ULP."""
    counted = [(k, v, load_summary(arch, dtype, k, v)) for k, v in entries]
    counted = [(k, v, s) for k, v, s in counted if s and s.get("outcomes")]
    if not counted:
        return ""
    kinds = sorted({k for _, _, s in counted for k in s["outcomes"]})
    head = "| Parameters | " + " | ".join(kinds) + " |\n"
    rule = "|------------" + "|------" * len(kinds) + "|\n"
    rows = [
        f"| `{params_desc(k, v)}` | "
        + " | ".join(f"{s['outcomes'].get(kind, 0):,}" for kind in kinds)
        + " |\n"
        for k, v, s in counted
    ]
    return "**Outcomes**\n\n" + head + rule + "".join(rows) + "\n"


def _sampling_note(dtype: str, entries: list[tuple[str, str]]) -> str:
    """A sampled maximum is a lower bound, and must never read as a bound.

    How a sweep samples follows from its arity and dtype, so it is looked up rather than
    carried through the data as a column that would be identical on every row.
    """
    info = describe(entries[0][0])
    how = SAMPLED.get((info.operands, dtype)) if info else None
    if not how:
        return ""
    return (
        f"> **Sampled, not exhaustive.** For this op {how}. The figures above are a lower "
        "bound on the error, and comparable between releases, but they are not a bound "
        "over the dtype.\n\n"
    )


def _provenance(arch: str, dtype: str, entries: list[tuple[str, str]]) -> str:
    """Only claim a run for ops that run actually covered — silence would read as fresh."""
    run = _get_index().get(RUNS_KEY, {}).get(arch, {}).get(dtype)
    if not run or not all(op_key in run["ops"] for op_key, _ in entries):
        return "> **Provenance unknown.** These figures predate run tracking. Re-measure to attribute them.\n\n"
    return (
        f"_Measured on {run['device_arch']} · tt-metal `{run['tt_metal_commit']}` · "
        f"ttnn `{run['ttnn_version']}` · run `{run['run_id']}`_\n\n"
    )


def op_detail_page(arch: str, dtype: str, display_name: str, entries: list[tuple[str, str]]) -> str:
    """reports/by_arch/{arch}/{dtype}/{display_name}.md
    entries = [(op_key, variant), ...] — all parameter sets for this op.
    """
    page_path = REPORTS_DIR / "by_arch" / arch / dtype / f"{display_name}.md"

    lines = [
        f"# {display_name} — {ARCH_DISPLAY.get(arch, arch)}, {DTYPE_DISPLAY.get(dtype, dtype)}\n",
        GENERATED_NOTE,
        f"**Architecture:** {ARCH_DISPLAY.get(arch, arch)}  \n",
        f"**Data type:** {DTYPE_DISPLAY.get(dtype, dtype)}  \n",
    ]
    lines.append("\n---\n\n")
    lines.append(
        f"[← {ARCH_DISPLAY.get(arch, arch)} {DTYPE_DISPLAY.get(dtype, dtype)} ops](README.md) | "
        f"[All archs for {display_name}](../../../by_op/{display_name}/README.md) | "
        f"[Top](../../../README.md)\n\n"
    )

    # Any entry will do: everything on this page shares a display_name, so one range
    range_text = _input_range_text(entries[0][0], dtype)
    lines.append(f"**Measured input range:** {range_text}  \n\n")

    # Only for unary ops: elsewhere x is one operand of several, and a bound on it would
    # describe the sampled partner rather than the input under test.
    info = describe(entries[0][0])
    unary = bool(info and info.operands == 1)
    head = "| Parameters | Max ULP | Mean ULP | Max abs error |"
    rule = "|------------|---------|----------|---------------|"
    if unary:
        head = head.replace("| Max abs", "| Accurate to \\|x\\| | Max abs")
        rule = rule.replace("|------------|---------|----------|", "|---|---|---|---|")
    lines.extend([head + "\n", rule + "\n"])
    for op_key, variant in entries:
        params = params_desc(op_key, variant)
        summary = load_summary(arch, dtype, op_key, variant)
        if not summary:
            lines.append(f"| `{params}` |" + " — |" * (4 if unary else 3) + "\n")
            continue
        clipped = " ⚠" if summary.get("ulp_clipped") else ""
        cells = [summary["max_ulp"] + clipped, summary["mean_ulp"]]
        if unary:
            cells.append(_usable_text(summary))
        cells.append(summary["max_abs"])
        lines.append(f"| `{params}` | " + " | ".join(cells) + " |\n")

    lines.append("\n")
    for op_key, variant in entries:
        s = load_summary(arch, dtype, op_key, variant)
        if s and s.get("verdict"):
            why = f" · _{s['rationale']}_" if s.get("rationale") else ""
            lines.append(f"**{params_desc(op_key, variant)}** — {s['verdict']}{why}  \n")
    lines.append("\n")
    lines.append(_outcome_table(arch, dtype, entries))
    lines.append(_specials_table(arch, dtype, entries))
    lines.append(_sampling_note(dtype, entries))
    lines.append(_provenance(arch, dtype, entries))

    # One chart per parameter set
    multi = len(entries) > 1
    for op_key, variant in entries:
        params = params_desc(op_key, variant)
        if multi:
            lines.append(f"### `{params}`\n\n")
        chart = chart_rel_path(arch, dtype, op_key, variant, page_path.parent)
        lines.append(f"![ULP error — {display_name} {params}]({chart})\n\n")

    return "".join(lines)


def arch_dtype_index(arch: str, dtype: str, ops: dict[str, list[str]]) -> str:
    """reports/by_arch/{arch}/{dtype}/README.md"""
    page_path = REPORTS_DIR / "by_arch" / arch / dtype / "README.md"
    groups = group_by_display(ops)

    lines = [
        f"# {ARCH_DISPLAY.get(arch, arch)} — {DTYPE_DISPLAY.get(dtype, dtype)}\n",
        GENERATED_NOTE,
        f"[← {ARCH_DISPLAY.get(arch, arch)}](../README.md) | [Top](../../../README.md)\n\n",
        "## Operations Summary\n\n",
        "_Accurate to \\|x\\|: the largest \\|x\\| within 2 ULP. `n/a` for ops of more than one "
        "operand, where a bound on x would describe its sampled partner instead._\n\n",
        "| Op | Parameters | Max ULP | Mean ULP | Accurate to \\|x\\| | Max abs error |\n",
        "|----|------------|---------|----------|-----------------|---------------|\n",
    ]

    for display_name, entries in groups.items():
        for i, (op_key, variant) in enumerate(entries):
            params = params_desc(op_key, variant)
            summary = load_summary(arch, dtype, op_key, variant)
            info = describe(op_key)
            max_ulp = (summary["max_ulp"] if summary else "—") + (
                " ⚠" if summary and summary.get("ulp_clipped") else ""
            )
            mean_ulp = summary["mean_ulp"] if summary else "—"
            if not summary:
                usable = "—"
            elif info and info.operands > 1:
                usable = "n/a"
            else:
                usable = _usable_text(summary)
            max_abs = summary["max_abs"] if summary else "—"
            op_cell = f"[{display_name}]({display_name}.md)" if i == 0 else ""
            lines.append(
                f"| {op_cell} | `{params}` | {max_ulp} | {mean_ulp} | {usable} | {max_abs} |\n"
            )

    lines.append("\n")
    lines.append(_unmeasured_table(arch, dtype))
    lines.append("\n---\n\n## Charts Preview\n\n")
    for display_name, entries in groups.items():
        lines.append(f"### [{display_name}]({display_name}.md)\n\n")
        for op_key, variant in entries:
            chart = chart_rel_path(arch, dtype, op_key, variant, page_path.parent)
            params = params_desc(op_key, variant)
            lines.append(f"![{display_name} {params}]({chart})\n\n")

    return "".join(lines)


def arch_index(arch: str, data_for_arch: dict) -> str:
    """reports/by_arch/{arch}/README.md"""
    groups = {d: group_by_display(data_for_arch.get(d, {})) for d in DTYPES}
    available_dtypes = [d for d in DTYPES if d in data_for_arch]

    lines = [
        f"# {ARCH_DISPLAY.get(arch, arch)}\n",
        GENERATED_NOTE,
        "[← Architectures](../README.md) | [Top](../../README.md)\n\n",
        "## Data Types\n\n",
    ]
    lines += [
        f"- [{DTYPE_DISPLAY.get(d, d)}]({d}/README.md) — {len(groups[d])} ops\n"
        for d in available_dtypes
    ]

    lines.append("\n## Quick Summary\n\n")
    lines.append(
        "| Op | "
        + " | ".join(f"[{DTYPE_DISPLAY.get(d, d)}]({d}/README.md)" for d in available_dtypes)
        + " |\n"
    )
    lines.append("|----" + "|------" * len(available_dtypes) + "|\n")

    for display_name in sorted(set().union(*(g.keys() for g in groups.values()))):
        cells = []
        for dtype in available_dtypes:
            group = groups[dtype].get(display_name)
            if not group:
                cells.append("—")
                continue
            summary = load_summary(arch, dtype, *group[0])
            label = f"{summary['max_ulp']} ULP" if summary else "data"
            cells.append(f"[{label}]({dtype}/{display_name}.md)")
        lines.append(f"| `{display_name}` | " + " | ".join(cells) + " |\n")

    return "".join(lines)


def arch_list_index(data: dict) -> str:
    lines = [
        "# By Architecture\n",
        GENERATED_NOTE,
        "[← Top](../README.md)\n\n",
        "| Architecture | bf16 ops | fp32 ops |\n",
        "|-------------|---------|----------|\n",
    ]
    for arch in sorted(data.keys()):
        bf16_n = len(group_by_display(data[arch].get("bf16", {})))
        fp32_n = len(group_by_display(data[arch].get("fp32", {})))
        lines.append(
            f"| [{ARCH_DISPLAY.get(arch, arch)}]({arch}/README.md) | {bf16_n} | {fp32_n} |\n"
        )
    return "".join(lines)


def op_cross_arch_page(display_name: str, data: dict) -> str:
    """reports/by_op/{display_name}/README.md — op across all arch/dtype"""
    page_path = REPORTS_DIR / "by_op" / display_name / "README.md"

    groups = {
        (a, d): group_by_display(data.get(a, {}).get(d, {})).get(display_name, [])
        for a in ARCHS
        for d in DTYPES
    }
    # (arch, dtype, op_key, variant) — display_name comes from this same data, so never empty.
    all_entries = [(a, d, k, v) for (a, d), g in groups.items() for k, v in g]

    lines = [
        f"# `{display_name}` — All Architectures & Data Types\n",
        GENERATED_NOTE,
        "[← All ops](../README.md) | [Top](../../README.md)\n\n",
    ]
    lines.append("\n")

    all_params = sorted(
        dict.fromkeys(params_desc(op_key, variant) for _, _, op_key, variant in all_entries)
    )
    available_archs = sorted(dict.fromkeys(a for a, _, _, _ in all_entries))
    available_dtypes = sorted(dict.fromkeys(d for _, d, _, _ in all_entries))

    header = (
        "| Parameters | Arch | "
        + " | ".join(DTYPE_DISPLAY.get(d, d) for d in available_dtypes)
        + " |\n"
    )
    sep = "|------------|------" + "|------" * len(available_dtypes) + "|\n"
    lines.extend([header, sep])

    for params in all_params:
        for arch in available_archs:
            cells = []
            for dtype in available_dtypes:
                entry = next(
                    ((k, v) for k, v in groups[arch, dtype] if params_desc(k, v) == params),
                    None,
                )
                if not entry:
                    cells.append("—")
                    continue
                summary = load_summary(arch, dtype, *entry)
                link = f"../../by_arch/{arch}/{dtype}/{display_name}.md"
                label = f"{summary['max_ulp']} ULP" if summary else "data"
                cells.append(f"[{label}]({link})")
            arch_label = ARCH_DISPLAY.get(arch, arch)
            lines.append(f"| `{params}` | {arch_label} | " + " | ".join(cells) + " |\n")

    lines.append("\n---\n\n## Charts\n\n")
    for arch in available_archs:
        for dtype in available_dtypes:
            group = groups[arch, dtype]
            if not group:
                continue
            lines.append(
                f"### {ARCH_DISPLAY.get(arch, arch)}, {DTYPE_DISPLAY.get(dtype, dtype)}\n\n"
            )
            for op_key, variant in group:
                params = params_desc(op_key, variant)
                chart = chart_rel_path(arch, dtype, op_key, variant, page_path.parent)
                lines.append(
                    f"**`{params}`**\n\n![{display_name} {params} {arch} {dtype}]({chart})\n\n"
                )

    return "".join(lines)


def op_list_index(data: dict) -> str:
    groups = {(a, d): group_by_display(data.get(a, {}).get(d, {})) for a in ARCHS for d in DTYPES}
    all_display = sorted(set().union(*(g.keys() for g in groups.values())))

    lines = [
        "# By Operation\n",
        GENERATED_NOTE,
        "[← Top](../README.md)\n\n",
        f"Total: {len(all_display)} ops measured\n\n",
        "| Op | Category | WH bf16 | WH fp32 | BH bf16 | BH fp32 |\n",
        "|----|----------|---------|---------|---------|----------|\n",
    ]

    for display_name in all_display:
        category = "—"
        cells = []
        for arch in ARCHS:
            for dtype in DTYPES:
                group = groups[arch, dtype].get(display_name)
                if not group:
                    cells.append("—")
                    continue
                op_key, variant = group[0]
                if category == "—":
                    category = get_op_category(op_key)
                summary = load_summary(arch, dtype, op_key, variant)
                link = f"{display_name}/README.md"
                cells.append(f"[{summary['max_ulp']}]({link})" if summary else f"[✓]({link})")
        lines.append(
            f"| [{display_name}]({display_name}/README.md) | {category} | "
            + " | ".join(cells)
            + " |\n"
        )

    return "".join(lines)


def dtype_index(dtype: str, data: dict) -> str:
    available_archs = sorted(arch for arch in data if dtype in data[arch])
    groups = {a: group_by_display(data[a][dtype]) for a in available_archs}
    all_display = sorted(set().union(*(g.keys() for g in groups.values())))

    lines = [
        f"# {DTYPE_DISPLAY.get(dtype, dtype)}\n",
        GENERATED_NOTE,
        "[← Dtypes](../README.md) | [Top](../../README.md)\n\n",
        "| Op | " + " | ".join(ARCH_DISPLAY.get(a, a) for a in available_archs) + " |\n",
        "|----" + "|------" * len(available_archs) + "|\n",
    ]

    for display_name in all_display:
        cells = []
        for arch in available_archs:
            group = groups[arch].get(display_name)
            if not group:
                cells.append("—")
                continue
            summary = load_summary(arch, dtype, *group[0])
            link = f"../../by_arch/{arch}/{dtype}/{display_name}.md"
            cells.append(f"[{summary['max_ulp']} ULP]({link})" if summary else f"[✓]({link})")
        lines.append(f"| `{display_name}` | " + " | ".join(cells) + " |\n")

    return "".join(lines)


def dtype_list_index(data: dict) -> str:
    lines = [
        "# By Data Type\n",
        GENERATED_NOTE,
        "[← Top](../README.md)\n\n",
    ]
    for dtype in DTYPES:
        n_wh = len(group_by_display(data.get("wh", {}).get(dtype, {})))
        n_bh = len(group_by_display(data.get("bh", {}).get(dtype, {})))
        lines.append(
            f"- [{DTYPE_DISPLAY.get(dtype, dtype)}]({dtype}/README.md)"
            f" — WH: {n_wh} ops, BH: {n_bh} ops\n"
        )
    return "".join(lines)


def top_readme(data: dict) -> str:
    groups = {(a, d): group_by_display(data.get(a, {}).get(d, {})) for a in data for d in DTYPES}
    total_archs = len(data)
    total_ops = len(set().union(*(g.keys() for g in groups.values())))

    lines = [
        "# TT-Metal Eltwise Op Accuracy Reports\n\n",
        GENERATED_NOTE,
        "Accuracy measurements for TT-Metal elementwise operations vs PyTorch golden reference.\n",
        "Charts show ULP (units in last place) error across the full input range.\n\n",
        "---\n\n",
        "## Browse Reports\n\n",
        "| View | Description |\n",
        "|------|-------------|\n",
        "| [By Architecture](by_arch/README.md) | Start from hardware platform (WH, BH), then dtype, then op |\n",
        "| [By Operation](by_op/README.md) | Start from op name, compare across architectures and dtypes |\n",
        "| [By Data Type](by_dtype/README.md) | Start from bf16 or fp32, see all ops on all archs |\n",
        "\n---\n\n",
        "## Quick Stats\n\n",
        "| Metric | Count |\n",
        "|--------|-------|\n",
        f"| Architectures measured | {total_archs} |\n",
        f"| Unique ops measured | {total_ops} |\n",
    ]
    for arch in sorted(data):
        for dtype in DTYPES:
            if n := len(groups[arch, dtype]):
                lines.append(
                    f"| {ARCH_DISPLAY.get(arch, arch)} {DTYPE_DISPLAY.get(dtype, dtype)} ops | {n} |\n"
                )

    lines.extend(
        [
            "\n---\n\n",
            "## Data Collection\n\n",
            "```bash\n",
            "# Collect measurements (run on target hardware)\n",
            "ttnn-accuracy measure --arch wh --category unary --dtype both\n",
            "\n",
            "# Generate SVG charts and update report_index.json\n",
            "ttnn-accuracy charts\n",
            "\n",
            "# Regenerate this report tree\n",
            "ttnn-accuracy report\n",
            "```\n",
        ]
    )
    return "".join(lines)


def generate_reports(arch_filter=None, dtype_filter=None, categories=None) -> int:
    if categories is None:
        categories = ["unary"]

    data = discover_ops(categories=categories)

    # data carries an entry per arch/dtype directory even when every op was filtered out.
    if not any(ops for dtypes in data.values() for ops in dtypes.values()):
        logger.error(
            "no charts matched categories={} — run `ttnn-accuracy charts` first", categories
        )
        return 1

    archs = [arch_filter] if arch_filter else sorted(data)
    dtypes = [dtype_filter] if dtype_filter else DTYPES
    grouped = {(a, d): group_by_display(data.get(a, {}).get(d, {})) for a in archs for d in dtypes}

    write(REPORTS_DIR / "README.md", top_readme(data))

    write(REPORTS_DIR / "by_arch" / "README.md", arch_list_index(data))
    for arch in archs:
        write(REPORTS_DIR / "by_arch" / arch / "README.md", arch_index(arch, data.get(arch, {})))
        for dtype in dtypes:
            write(
                REPORTS_DIR / "by_arch" / arch / dtype / "README.md",
                arch_dtype_index(arch, dtype, data.get(arch, {}).get(dtype, {})),
            )
            for display_name, entries in grouped[arch, dtype].items():
                write(
                    REPORTS_DIR / "by_arch" / arch / dtype / f"{display_name}.md",
                    op_detail_page(arch, dtype, display_name, entries),
                )

    write(REPORTS_DIR / "by_op" / "README.md", op_list_index(data))
    for display_name in sorted(set().union(*(g.keys() for g in grouped.values()))):
        write(
            REPORTS_DIR / "by_op" / display_name / "README.md",
            op_cross_arch_page(display_name, data),
        )

    write(REPORTS_DIR / "by_dtype" / "README.md", dtype_list_index(data))
    for dtype in dtypes:
        write(REPORTS_DIR / "by_dtype" / dtype / "README.md", dtype_index(dtype, data))

    logger.success("report tree regenerated")
    return 0
