#!/usr/bin/env python3
"""
Generate the full reports/ markdown tree from data/ and charts/.

Scans data/ and reports/charts/ to discover what has been measured,
then produces:
  reports/README.md                     - top-level navigation
  reports/by_arch/{arch}/README.md      - per-arch overview
  reports/by_arch/{arch}/{dtype}/README.md  - per-arch+dtype all ops
  reports/by_arch/{arch}/{dtype}/{op}.md    - single op detail page
  reports/by_op/{op}/README.md          - op across all arch/dtype
  reports/by_dtype/{dtype}/README.md    - dtype across all ops/arch

Usage:
    python generate_reports.py
    python generate_reports.py --arch wh --dtype bf16
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional

import pandas as pd

REPO_ROOT = Path(__file__).parent.parent
DATA_DIR = REPO_ROOT / "data"
CHARTS_DIR = REPO_ROOT / "reports" / "charts"
REPORTS_DIR = REPO_ROOT / "reports"

ARCHS = ["wh", "bh"]
DTYPES = ["bf16", "fp32"]

ARCH_DISPLAY = {"wh": "Wormhole (WH)", "bh": "Blackhole (BH)"}
DTYPE_DISPLAY = {"bf16": "bfloat16", "fp32": "float32"}

GENERATED_NOTE = (
    "_This page is auto-generated by `scripts/generate_reports.py`. "
    "Do not edit manually._\n\n"
    f"_Generated: {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}_\n\n"
)


# ---------------------------------------------------------------------------
# Discovery helpers
# ---------------------------------------------------------------------------

_registry_cache: dict | None = None

def _get_registry() -> dict:
    global _registry_cache
    if _registry_cache is None:
        sys.path.insert(0, str(Path(__file__).parent))
        try:
            from ops_registry import get_registry
            _registry_cache = get_registry()
        except Exception:
            _registry_cache = {}
    return _registry_cache


def get_op_category(op_name: str) -> str:
    reg = _get_registry()
    return reg[op_name].category if op_name in reg else "unknown"


def discover_data(categories: list[str] | None = None) -> dict:
    """Return nested dict: arch -> dtype -> op_name -> [variant_names].

    categories: if given, only include ops whose registry category is in the list.
    """
    result: dict = {}
    if not DATA_DIR.exists():
        return result
    for arch_dir in sorted(DATA_DIR.iterdir()):
        if not arch_dir.is_dir():
            continue
        arch = arch_dir.name
        result[arch] = {}
        for dtype_dir in sorted(arch_dir.iterdir()):
            if not dtype_dir.is_dir():
                continue
            dtype = dtype_dir.name
            result[arch][dtype] = {}
            for op_dir in sorted(dtype_dir.iterdir()):
                if not op_dir.is_dir():
                    continue
                op = op_dir.name
                if categories and get_op_category(op) not in categories:
                    continue
                variants = [f.stem for f in sorted(op_dir.glob("*.csv"))]
                if variants:
                    result[arch][dtype][op] = variants
    return result


def chart_rel_path(arch: str, dtype: str, op: str, variant: str, from_dir: Path) -> str:
    """Return relative path to SVG chart from a given directory."""
    chart = CHARTS_DIR / arch / dtype / f"{op}_{variant}_ulp.svg"
    if chart.exists():
        # Calculate relative path from from_dir to chart
        # Both paths are under REPORTS_DIR, so we can construct the relative path manually
        from_rel = from_dir.relative_to(REPORTS_DIR) if REPORTS_DIR in from_dir.parents else from_dir
        chart_rel = chart.relative_to(REPORTS_DIR)
        # Count how many levels up we need to go from from_dir
        up_levels = len(from_rel.parts)
        rel_path = Path("/".join([".."] * up_levels)) / chart_rel
        return str(rel_path)
    return ""


def load_summary(arch: str, dtype: str, op: str, variant: str) -> dict | None:
    """Load summary stats from CSV, restricted to the op's display range."""
    csv_path = DATA_DIR / arch / dtype / op / f"{variant}.csv"
    if not csv_path.exists():
        return None
    try:
        df = pd.read_csv(csv_path, index_col="index")
        # Filter to display range so out-of-domain rows don't inflate stats
        reg = _get_registry()
        if op in reg:
            d_lo, d_hi = reg[op].input_range.display_bounds()
            if d_lo not in (None, float("-inf")):
                df = df[df["x"] >= d_lo]
            if d_hi not in (None, float("inf")):
                df = df[df["x"] <= d_hi]
        if df.empty:
            return None
        ulp_col = df["max_ulp_error"].replace([float("inf"), float("-inf")], float("nan"))
        max_ulp_val = ulp_col.max()
        n_clipped = int((ulp_col > 1000).sum())
        individual = len(df) > 5000  # bf16 individual-point format
        return {
            "max_ulp": f"{max_ulp_val:.3g}" if max_ulp_val == max_ulp_val else "—",
            "mean_ulp": f"{ulp_col.mean():.3g}",
            "max_abs": f"{df['max_abs_error'].max():.3g}",
            "ulp_clipped": n_clipped,
            "n_inputs": len(df),
            "individual": individual,
        }
    except Exception:
        return None


def get_op_display_name(op_name: str) -> str:
    reg = _get_registry()
    return reg[op_name].display_name if op_name in reg else op_name


def get_op_note(op_name: str) -> str:
    reg = _get_registry()
    return reg[op_name].input_range.note if op_name in reg else ""


def get_op_description(op_name: str) -> str:
    reg = _get_registry()
    return reg[op_name].description if op_name in reg else ""


# ---------------------------------------------------------------------------
# Page builders
# ---------------------------------------------------------------------------

def write(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"  Wrote {path.relative_to(REPO_ROOT)}")


def op_detail_page(arch: str, dtype: str, op: str, variants: list[str], data: dict) -> str:
    """Single op detail page: reports/by_arch/{arch}/{dtype}/{op}.md"""
    page_path = REPORTS_DIR / "by_arch" / arch / dtype / f"{op}.md"
    display = get_op_display_name(op)
    note = get_op_note(op)
    desc = get_op_description(op)

    lines = [
        f"# {display} — {ARCH_DISPLAY.get(arch, arch)}, {DTYPE_DISPLAY.get(dtype, dtype)}\n",
        GENERATED_NOTE,
        f"**Operation:** `{op}`  \n",
        f"**Architecture:** {ARCH_DISPLAY.get(arch, arch)}  \n",
        f"**Data type:** {DTYPE_DISPLAY.get(dtype, dtype)}  \n",
    ]
    if note:
        lines.append(f"**Valid domain:** {note}  \n")
    if desc:
        lines.append(f"**Notes:** {desc}  \n")
    lines.append("\n---\n\n")

    # Navigation breadcrumb
    lines.append(
        f"[← {ARCH_DISPLAY.get(arch, arch)} {DTYPE_DISPLAY.get(dtype, dtype)} ops](README.md) | "
        f"[All archs for {display}](../../../by_op/{op}/README.md) | "
        f"[Top](../../../README.md)\n\n"
    )

    for variant in variants:
        variant_display = variant.replace("_", " ")
        lines.append(f"## Variant: `{variant_display}`\n\n")

        summary = load_summary(arch, dtype, op, variant)
        if summary:
            clipped_note = (f" ⚠ ({summary['ulp_clipped']} groups > 1000 ULP, "
                            f"see max abs error)" if summary.get("ulp_clipped") else "")
            lines.extend([
                "| Metric | Value |\n",
                "|--------|-------|\n",
                f"| Max ULP error (display range) | {summary['max_ulp']}{clipped_note} |\n",
                f"| Mean ULP error (display range) | {summary['mean_ulp']} |\n",
                f"| Max absolute error | {summary['max_abs']} |\n",
                "\n",
            ])

        chart = chart_rel_path(arch, dtype, op, variant, page_path.parent)
        if chart:
            lines.append(f"![ULP error chart for {op} {variant}]({chart})\n\n")
        else:
            lines.append(f"_Chart not yet generated. Run `scripts/generate_charts.py`._\n\n")

    return "".join(lines)


def arch_dtype_index(arch: str, dtype: str, ops: dict[str, list[str]]) -> str:
    """Index page: reports/by_arch/{arch}/{dtype}/README.md"""
    page_path = REPORTS_DIR / "by_arch" / arch / dtype / "README.md"

    lines = [
        f"# {ARCH_DISPLAY.get(arch, arch)} — {DTYPE_DISPLAY.get(dtype, dtype)}\n",
        GENERATED_NOTE,
        f"[← {ARCH_DISPLAY.get(arch, arch)}](../README.md) | [Top](../../../README.md)\n\n",
        "## Operations Summary\n\n",
        "| Op | Variant | Max ULP | Mean ULP | Details |\n",
        "|----|---------|---------|----------|---------|\n",
    ]

    for op, variants in sorted(ops.items()):
        display = get_op_display_name(op)
        for i, variant in enumerate(variants):
            summary = load_summary(arch, dtype, op, variant)
            max_ulp = summary["max_ulp"] if summary else "—"
            mean_ulp = summary["mean_ulp"] if summary else "—"
            op_cell = f"`{display}`" if i == 0 else ""
            detail_link = f"[{op}.md]({op}.md)" if i == 0 else ""
            lines.append(f"| {op_cell} | {variant} | {max_ulp} | {mean_ulp} | {detail_link} |\n")

    lines.append("\n---\n\n## Charts Preview\n\n")

    for op, variants in sorted(ops.items()):
        display = get_op_display_name(op)
        lines.append(f"### [{display}]({op}.md)\n\n")
        for variant in variants:
            chart = chart_rel_path(arch, dtype, op, variant, page_path.parent)
            if chart:
                lines.append(f"![{op} {variant}]({chart})\n\n")

    return "".join(lines)


def arch_index(arch: str, data_for_arch: dict) -> str:
    """Per-arch overview: reports/by_arch/{arch}/README.md"""
    lines = [
        f"# {ARCH_DISPLAY.get(arch, arch)}\n",
        GENERATED_NOTE,
        "[← Architectures](../README.md) | [Top](../../README.md)\n\n",
        "## Data Types\n\n",
    ]
    for dtype in DTYPES:
        if dtype in data_for_arch:
            n_ops = len(data_for_arch[dtype])
            lines.append(f"- [{DTYPE_DISPLAY.get(dtype, dtype)}]({dtype}/README.md) — {n_ops} ops\n")

    lines.append("\n## Quick Summary\n\n")
    lines.append("| Op | " + " | ".join(
        f"[{DTYPE_DISPLAY.get(d, d)}]({d}/README.md)" for d in DTYPES if d in data_for_arch
    ) + " |\n")
    lines.append("|----" + "|------" * sum(1 for d in DTYPES if d in data_for_arch) + "|\n")

    all_ops = sorted(set().union(*(data_for_arch.get(d, {}).keys() for d in DTYPES)))
    for op in all_ops:
        display = get_op_display_name(op)
        cells = []
        for dtype in DTYPES:
            if dtype not in data_for_arch or op not in data_for_arch[dtype]:
                cells.append("—")
            else:
                variants = data_for_arch[dtype][op]
                summary = load_summary(arch, dtype, op, variants[0])
                if summary:
                    cells.append(f"[{summary['max_ulp']} ULP]({dtype}/{op}.md)")
                else:
                    cells.append(f"[data]({dtype}/{op}.md)")
        lines.append(f"| `{display}` | " + " | ".join(cells) + " |\n")

    return "".join(lines)


def arch_list_index(data: dict) -> str:
    """reports/by_arch/README.md"""
    lines = [
        "# By Architecture\n",
        GENERATED_NOTE,
        "[← Top](../README.md)\n\n",
        "| Architecture | bf16 ops | fp32 ops |\n",
        "|-------------|---------|----------|\n",
    ]
    for arch in sorted(data.keys()):
        bf16_n = len(data[arch].get("bf16", {}))
        fp32_n = len(data[arch].get("fp32", {}))
        lines.append(f"| [{ARCH_DISPLAY.get(arch, arch)}]({arch}/README.md) | {bf16_n} | {fp32_n} |\n")
    return "".join(lines)


def op_cross_arch_page(op: str, data: dict) -> str:
    """reports/by_op/{op}/README.md - op across all arch/dtype"""
    display = get_op_display_name(op)
    note = get_op_note(op)
    desc = get_op_description(op)
    page_path = REPORTS_DIR / "by_op" / op / "README.md"

    lines = [
        f"# `{display}` — All Architectures & Dtypes\n",
        GENERATED_NOTE,
        "[← All ops](../README.md) | [Top](../../README.md)\n\n",
    ]
    if note:
        lines.append(f"**Valid domain:** {note}  \n")
    if desc:
        lines.append(f"**Notes:** {desc}  \n")
    lines.append("\n")

    # Summary table: arch x dtype, max ULP
    available_archs = sorted(arch for arch in data if any(op in data[arch].get(d, {}) for d in DTYPES))
    if not available_archs:
        lines.append("_No data available yet._\n")
        return "".join(lines)

    header = "| Variant | Arch | " + " | ".join(DTYPE_DISPLAY.get(d, d) for d in DTYPES) + " |\n"
    sep = "|---------|------|" + "|------" * len(DTYPES) + "|\n"
    lines.extend([header, sep])

    all_variants = sorted(set().union(*(
        data.get(arch, {}).get(dtype, {}).get(op, [])
        for arch in available_archs
        for dtype in DTYPES
    )))

    for variant in all_variants:
        for arch in available_archs:
            cells = []
            for dtype in DTYPES:
                if op in data.get(arch, {}).get(dtype, {}):
                    summary = load_summary(arch, dtype, op, variant)
                    link = f"../../by_arch/{arch}/{dtype}/{op}.md"
                    if summary:
                        cells.append(f"[{summary['max_ulp']} ULP]({link})")
                    else:
                        cells.append(f"[data]({link})")
                else:
                    cells.append("—")
            lines.append(f"| {variant} | {ARCH_DISPLAY.get(arch, arch)} | " + " | ".join(cells) + " |\n")

    lines.append("\n---\n\n## Charts\n\n")
    for arch in available_archs:
        for dtype in DTYPES:
            if op not in data.get(arch, {}).get(dtype, {}):
                continue
            variants = data[arch][dtype][op]
            lines.append(f"### {ARCH_DISPLAY.get(arch, arch)}, {DTYPE_DISPLAY.get(dtype, dtype)}\n\n")
            for variant in variants:
                chart = chart_rel_path(arch, dtype, op, variant, page_path.parent)
                if chart:
                    lines.append(f"![{op} {variant} {arch} {dtype}]({chart})\n\n")

    return "".join(lines)


def op_list_index(data: dict) -> str:
    """reports/by_op/README.md"""
    all_ops = sorted(set().union(*(
        data.get(arch, {}).get(dtype, {}).keys()
        for arch in data
        for dtype in DTYPES
    )))

    lines = [
        "# By Operation\n",
        GENERATED_NOTE,
        "[← Top](../README.md)\n\n",
        f"Total: {len(all_ops)} ops measured\n\n",
        "| Op | Category | WH bf16 | WH fp32 | BH bf16 | BH fp32 |\n",
        "|----|----------|---------|---------|---------|----------|\n",
    ]

    for op in all_ops:
        display = get_op_display_name(op)
        category = get_op_category(op)
        cells = []
        for arch in ARCHS:
            for dtype in DTYPES:
                if op in data.get(arch, {}).get(dtype, {}):
                    variants = data[arch][dtype][op]
                    summary = load_summary(arch, dtype, op, variants[0])
                    link = f"{op}/README.md"
                    if summary:
                        cells.append(f"[{summary['max_ulp']}]({link})")
                    else:
                        cells.append(f"[✓]({link})")
                else:
                    cells.append("—")
        lines.append(f"| [{display}]({op}/README.md) | {category} | " + " | ".join(cells) + " |\n")

    return "".join(lines)


def dtype_index(dtype: str, data: dict) -> str:
    """reports/by_dtype/{dtype}/README.md"""
    all_ops = sorted(set().union(*(
        data.get(arch, {}).get(dtype, {}).keys()
        for arch in data
    )))

    available_archs = sorted(arch for arch in data if dtype in data[arch])

    lines = [
        f"# {DTYPE_DISPLAY.get(dtype, dtype)}\n",
        GENERATED_NOTE,
        "[← Dtypes](../README.md) | [Top](../../README.md)\n\n",
        "| Op | " + " | ".join(ARCH_DISPLAY.get(a, a) for a in available_archs) + " |\n",
        "|----|" + "|------" * len(available_archs) + "|\n",
    ]

    for op in all_ops:
        display = get_op_display_name(op)
        cells = []
        for arch in available_archs:
            if op in data.get(arch, {}).get(dtype, {}):
                variants = data[arch][dtype][op]
                summary = load_summary(arch, dtype, op, variants[0])
                link = f"../../by_arch/{arch}/{dtype}/{op}.md"
                if summary:
                    cells.append(f"[{summary['max_ulp']} ULP]({link})")
                else:
                    cells.append(f"[✓]({link})")
            else:
                cells.append("—")
        lines.append(f"| `{display}` | " + " | ".join(cells) + " |\n")

    return "".join(lines)


def dtype_list_index(data: dict) -> str:
    """reports/by_dtype/README.md"""
    lines = [
        "# By Data Type\n",
        GENERATED_NOTE,
        "[← Top](../README.md)\n\n",
    ]
    for dtype in DTYPES:
        n_wh = len(data.get("wh", {}).get(dtype, {}))
        n_bh = len(data.get("bh", {}).get(dtype, {}))
        lines.append(
            f"- [{DTYPE_DISPLAY.get(dtype, dtype)}]({dtype}/README.md)"
            f" — WH: {n_wh} ops, BH: {n_bh} ops\n"
        )
    return "".join(lines)


def top_readme(data: dict) -> str:
    """reports/README.md — main navigation page."""
    total_archs = len(data)
    total_ops = len(set().union(*(
        data.get(arch, {}).get(dtype, {}).keys()
        for arch in data
        for dtype in DTYPES
    )))

    lines = [
        "# TT-Metal Eltwise Op Accuracy Reports\n\n",
        GENERATED_NOTE,
        "Accuracy measurements for TT-Metal elementwise operations vs PyTorch golden reference.\n",
        "Charts show ULP (units in last place) error across the full input range.\n\n",
        "**ULP thresholds:**  \n",
        "- ≤ 1 ULP — excellent (bit-accurate)  \n",
        "- ≤ 3 ULP — accurate  \n",
        "- ≤ 10 ULP — approximate  \n",
        "- > 10 ULP — poor  \n\n",
        "---\n\n",
        "## Browse Reports\n\n",
        "| View | Description |\n",
        "|------|-------------|\n",
        "| [By Architecture](by_arch/README.md) | Start from hardware platform (WH, BH), then choose dtype and op |\n",
        "| [By Operation](by_op/README.md) | Start from op name, compare across architectures and dtypes |\n",
        "| [By Data Type](by_dtype/README.md) | Start from bf16 or fp32, see all ops on all archs |\n",
        "\n---\n\n",
        "## Quick Stats\n\n",
        f"| Metric | Count |\n",
        f"|--------|-------|\n",
        f"| Architectures measured | {total_archs} |\n",
        f"| Unique ops measured | {total_ops} |\n",
    ]

    for arch in sorted(data.keys()):
        for dtype in DTYPES:
            n = len(data.get(arch, {}).get(dtype, {}))
            if n:
                lines.append(f"| {ARCH_DISPLAY.get(arch, arch)} {DTYPE_DISPLAY.get(dtype, dtype)} ops | {n} |\n")

    lines.extend([
        "\n---\n\n",
        "## Data Collection\n\n",
        "```bash\n",
        "# Collect measurements (run on target hardware)\n",
        "python scripts/measure_accuracy.py --arch wh --ops all --dtype both\n",
        "python scripts/measure_accuracy.py --arch bh --ops all --dtype both\n",
        "\n",
        "# Generate SVG charts\n",
        "python scripts/generate_charts.py\n",
        "\n",
        "# Regenerate this report tree\n",
        "python scripts/generate_reports.py\n",
        "```\n",
    ])

    return "".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def generate_reports(arch_filter=None, dtype_filter=None, categories=None):
    sys.path.insert(0, str(Path(__file__).parent))
    if categories is None:
        categories = ["unary"]  # default: forward unary only

    data = discover_data(categories=categories)

    if not data:
        print("No data found in data/. Run measure_accuracy.py first.")
        print("Generating skeleton navigation pages...")

    # Top-level README
    write(REPORTS_DIR / "README.md", top_readme(data))

    # by_arch
    write(REPORTS_DIR / "by_arch" / "README.md", arch_list_index(data))
    for arch in (([arch_filter] if arch_filter else sorted(data.keys())) or ARCHS):
        arch_data = data.get(arch, {})
        write(REPORTS_DIR / "by_arch" / arch / "README.md", arch_index(arch, arch_data))
        for dtype in ([dtype_filter] if dtype_filter else DTYPES):
            dtype_ops = arch_data.get(dtype, {})
            write(REPORTS_DIR / "by_arch" / arch / dtype / "README.md",
                  arch_dtype_index(arch, dtype, dtype_ops))
            for op, variants in dtype_ops.items():
                write(
                    REPORTS_DIR / "by_arch" / arch / dtype / f"{op}.md",
                    op_detail_page(arch, dtype, op, variants, data),
                )

    # by_op
    write(REPORTS_DIR / "by_op" / "README.md", op_list_index(data))
    all_ops = sorted(set().union(*(
        data.get(arch, {}).get(dtype, {}).keys()
        for arch in data
        for dtype in DTYPES
    )))
    for op in all_ops:
        write(REPORTS_DIR / "by_op" / op / "README.md", op_cross_arch_page(op, data))

    # by_dtype
    write(REPORTS_DIR / "by_dtype" / "README.md", dtype_list_index(data))
    for dtype in ([dtype_filter] if dtype_filter else DTYPES):
        write(REPORTS_DIR / "by_dtype" / dtype / "README.md", dtype_index(dtype, data))

    print("\nDone.")


def parse_args():
    p = argparse.ArgumentParser(description="Generate markdown report tree")
    p.add_argument("--arch", help="Filter by architecture")
    p.add_argument("--dtype", help="Filter by dtype")
    p.add_argument("--categories", default="unary",
                   help="Comma-separated op categories to include "
                        "(default: unary; options: unary,binary,unary_bw)")
    return p.parse_args()


def main():
    args = parse_args()
    cats = [c.strip() for c in args.categories.split(",")]
    generate_reports(arch_filter=args.arch, dtype_filter=args.dtype, categories=cats)


if __name__ == "__main__":
    main()
