#!/usr/bin/env python3
"""
Generate the full reports/ markdown tree from report_index.json and reports/charts/.

Source of truth for what pages exist: reports/charts/{arch}/{dtype}/*.svg
Source of truth for summary stats:    report_index.json  (committed, updated by generate_charts.py)

Ops that share a display_name (e.g. celu_alpha0p5/1p0/2p0 all display as "celu")
are grouped onto a single page with one section per parameter set.

Usage:
    python generate_reports.py
    python generate_reports.py --arch wh --dtype bf16
    python generate_reports.py --categories unary,binary
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
CHARTS_DIR = REPO_ROOT / "reports" / "charts"
REPORTS_DIR = REPO_ROOT / "reports"
INDEX_FILE = REPO_ROOT / "report_index.json"

ARCHS = ["wh", "bh"]
DTYPES = ["bf16", "fp32"]

ARCH_DISPLAY = {"wh": "Wormhole (WH)", "bh": "Blackhole (BH)"}
DTYPE_DISPLAY = {"bf16": "bfloat16", "fp32": "float32"}

GENERATED_NOTE = (
    "_This page is auto-generated by `scripts/generate_reports.py`. "
    "Do not edit manually._\n\n"
    f"_Generated: {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}_\n\n"
)


# ---------------------------------------------------------------------------
# Registry / index helpers
# ---------------------------------------------------------------------------

_registry_cache: dict | None = None
_index_cache: dict | None = None


def _get_registry() -> dict:
    global _registry_cache
    if _registry_cache is None:
        sys.path.insert(0, str(Path(__file__).parent))
        try:
            from ops_registry import get_registry
            _registry_cache = get_registry()
        except Exception:
            _registry_cache = {}
    return _registry_cache


def _get_index() -> dict:
    global _index_cache
    if _index_cache is None:
        _index_cache = json.loads(INDEX_FILE.read_text()) if INDEX_FILE.exists() else {}
    return _index_cache


def get_op_category(op_key: str) -> str:
    reg = _get_registry()
    return reg[op_key].category if op_key in reg else "unknown"


def get_display_name(op_key: str) -> str:
    reg = _get_registry()
    return reg[op_key].display_name if op_key in reg else op_key


def get_op_note(op_key: str) -> str:
    reg = _get_registry()
    return reg[op_key].input_range.note if op_key in reg else ""


def get_op_description(op_key: str) -> str:
    reg = _get_registry()
    return reg[op_key].description if op_key in reg else ""


def get_params_desc(op_key: str, variant_key: str) -> str:
    """Return the human-readable params_desc for a variant (inverse of the filename sanitisation)."""
    reg = _get_registry()
    if op_key not in reg:
        return variant_key
    for v in reg[op_key].variants:
        sanitized = v.params_desc.replace(" ", "_").replace(",", "_").replace("=", "")
        if sanitized == variant_key:
            return v.params_desc
    return variant_key


def load_summary(arch: str, dtype: str, op_key: str, variant: str) -> dict | None:
    """Load summary stats from report_index.json."""
    stats = _get_index().get(arch, {}).get(dtype, {}).get(op_key, {}).get(variant)
    return dict(stats) if stats else None


def _input_range_text(op_key: str) -> str:
    """Human-readable description of the measured input range."""
    reg = _get_registry()
    if op_key not in reg:
        return "all normal values"
    r = reg[op_key].input_range
    lo, hi = r.lo, r.hi
    MIN_NORMAL = 2**-126
    MAX_NORMAL = 3.4e38

    def _s(v):
        if abs(v) == float("inf"):
            return None
        if abs(v) <= MIN_NORMAL * 2:
            return "0" if v == 0 else ("min\_normal" if v > 0 else "\-min\_normal")
        return f"{v:.4g}"

    if lo == float("-inf") and hi == float("inf"):
        return "all normal values"
    if lo == float("-inf"):
        s_hi = _s(hi)
        return f"x ≤ {s_hi}" if s_hi else "all normal values"
    if hi == float("inf"):
        s_lo = _s(lo)
        return f"x ≥ {s_lo}" if s_lo else "all normal values"
    return f"x ∈ [{_s(lo)}, {_s(hi)}]"


# ---------------------------------------------------------------------------
# Discovery: raw op_key → variants, grouped by display_name
# ---------------------------------------------------------------------------

def discover_ops(categories: list[str] | None = None) -> dict:
    """Return nested dict: arch -> dtype -> op_key -> [variant_names].

    Uses reports/charts/ as inventory so works without local data/.
    Categories filter is applied via ops_registry.
    """
    result: dict = {}
    if not CHARTS_DIR.exists():
        return result
    for arch_dir in sorted(CHARTS_DIR.iterdir()):
        if not arch_dir.is_dir():
            continue
        arch = arch_dir.name
        result[arch] = {}
        for dtype_dir in sorted(arch_dir.iterdir()):
            if not dtype_dir.is_dir():
                continue
            dtype = dtype_dir.name
            result[arch][dtype] = {}
            for op_key, variants_dict in sorted(_get_index().get(arch, {}).get(dtype, {}).items()):
                if categories and get_op_category(op_key) not in categories:
                    continue
                existing = [
                    v for v in sorted(variants_dict.keys())
                    if (dtype_dir / f"{op_key}_{v}_ulp.svg").exists()
                ]
                if existing:
                    result[arch][dtype][op_key] = existing
    return result


def group_by_display(ops: dict[str, list[str]]) -> dict[str, list[tuple[str, str]]]:
    """Group {op_key: [variants]} by display_name.
    Returns {display_name: [(op_key, variant), ...]} sorted by params_desc.
    """
    groups: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for op_key, variants in ops.items():
        display = get_display_name(op_key)
        for v in variants:
            groups[display].append((op_key, v))
    # Sort within each group by the human-readable params_desc
    return {d: sorted(entries, key=lambda e: get_params_desc(e[0], e[1]))
            for d, entries in sorted(groups.items())}


# ---------------------------------------------------------------------------
# Chart path
# ---------------------------------------------------------------------------

def chart_rel_path(arch: str, dtype: str, op_key: str, variant: str, from_dir: Path) -> str:
    chart = CHARTS_DIR / arch / dtype / f"{op_key}_{variant}_ulp.svg"
    if not chart.exists():
        return ""
    from_rel = from_dir.relative_to(REPORTS_DIR) if REPORTS_DIR in from_dir.parents else from_dir
    chart_rel = chart.relative_to(REPORTS_DIR)
    up_levels = len(from_rel.parts)
    return str(Path("/".join([".."] * up_levels)) / chart_rel)


# ---------------------------------------------------------------------------
# Page builders
# ---------------------------------------------------------------------------

def write(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"  Wrote {path.relative_to(REPO_ROOT)}")


def op_detail_page(arch: str, dtype: str, display_name: str,
                   entries: list[tuple[str, str]]) -> str:
    """reports/by_arch/{arch}/{dtype}/{display_name}.md
    entries = [(op_key, variant), ...] — all parameter sets for this op.
    """
    page_path = REPORTS_DIR / "by_arch" / arch / dtype / f"{display_name}.md"

    # For grouped pages, only show notes/descs that are shared across all entries
    # (per-variant descriptions are already visible in the params table)
    all_notes = [get_op_note(k) for k, _ in entries]
    all_descs = [get_op_description(k) for k, _ in entries]
    notes = [all_notes[0]] if all_notes and all(n == all_notes[0] for n in all_notes) and all_notes[0] else []
    descs = [all_descs[0]] if all_descs and all(d == all_descs[0] for d in all_descs) and all_descs[0] else []

    lines = [
        f"# {display_name} — {ARCH_DISPLAY.get(arch, arch)}, {DTYPE_DISPLAY.get(dtype, dtype)}\n",
        GENERATED_NOTE,
        f"**Architecture:** {ARCH_DISPLAY.get(arch, arch)}  \n",
        f"**Data type:** {DTYPE_DISPLAY.get(dtype, dtype)}  \n",
    ]
    for note in notes:
        lines.append(f"**Valid domain:** {note}  \n")
    for desc in descs:
        lines.append(f"**Notes:** {desc}  \n")
    lines.append("\n---\n\n")
    lines.append(
        f"[← {ARCH_DISPLAY.get(arch, arch)} {DTYPE_DISPLAY.get(dtype, dtype)} ops](README.md) | "
        f"[All archs for {display_name}](../../../by_op/{display_name}/README.md) | "
        f"[Top](../../../README.md)\n\n"
    )

    # Summary table (all params in one table)
    # Input range (same for all entries sharing a display_name)
    range_text = _input_range_text(entries[0][0])
    lines.append(f"**Measured input range:** {range_text}  \n\n")

    lines.extend([
        "| Parameters | Max ULP | Mean ULP | Max abs error |\n",
        "|------------|---------|----------|---------------|\n",
    ])
    for op_key, variant in entries:
        params = get_params_desc(op_key, variant)
        summary = load_summary(arch, dtype, op_key, variant)
        if summary:
            clipped = " ⚠" if summary.get("ulp_clipped") else ""
            lines.append(
                f"| `{params}` | {summary['max_ulp']}{clipped} "
                f"| {summary['mean_ulp']} | {summary['max_abs']} |\n"
            )
        else:
            lines.append(f"| `{params}` | — | — | — |\n")

    lines.append("\n")

    # Near-zero atol notes (one per entry if present)
    for op_key, variant in entries:
        params = get_params_desc(op_key, variant)
        summary = load_summary(arch, dtype, op_key, variant)
        nz = summary.get("near_zero_atol") if summary else None
        if nz:
            pstr = f" (`{params}`)" if len(entries) > 1 else ""
            lines.append(
                f"> **Note{pstr}:** ULP is not a useful metric near x ≈ 0 because the "
                f"output itself is near zero. "
                f"In x ∈ [{nz['x_lo']}, {nz['x_hi']}] "
                f"({nz['n']} inputs): max absolute error = **{nz['max_abs']}**.\n\n"
            )


    # One chart per parameter set
    multi = len(entries) > 1
    for op_key, variant in entries:
        params = get_params_desc(op_key, variant)
        if multi:
            lines.append(f"### `{params}`\n\n")
        chart = chart_rel_path(arch, dtype, op_key, variant, page_path.parent)
        if chart:
            lines.append(f"![ULP error — {display_name} {params}]({chart})\n\n")
        else:
            lines.append("_Chart not yet generated._\n\n")

    return "".join(lines)


def arch_dtype_index(arch: str, dtype: str, ops: dict[str, list[str]]) -> str:
    """reports/by_arch/{arch}/{dtype}/README.md"""
    page_path = REPORTS_DIR / "by_arch" / arch / dtype / "README.md"
    groups = group_by_display(ops)

    lines = [
        f"# {ARCH_DISPLAY.get(arch, arch)} — {DTYPE_DISPLAY.get(dtype, dtype)}\n",
        GENERATED_NOTE,
        f"[← {ARCH_DISPLAY.get(arch, arch)}](../README.md) | [Top](../../../README.md)\n\n",
        "## Operations Summary\n\n",
        "| Op | Parameters | Max ULP | Mean ULP | Max abs error |\n",
        "|----|------------|---------|----------|---------------|\n",
    ]

    for display_name, entries in groups.items():
        for i, (op_key, variant) in enumerate(entries):
            params = get_params_desc(op_key, variant)
            summary = load_summary(arch, dtype, op_key, variant)
            max_ulp  = (summary["max_ulp"]  if summary else "—") + (" ⚠" if summary and summary.get("ulp_clipped") else "")
            mean_ulp = summary["mean_ulp"] if summary else "—"
            max_abs  = summary["max_abs"]  if summary else "—"
            op_cell  = f"[{display_name}]({display_name}.md)" if i == 0 else ""
            lines.append(f"| {op_cell} | `{params}` | {max_ulp} | {mean_ulp} | {max_abs} |\n")

    lines.append("\n---\n\n## Charts Preview\n\n")
    for display_name, entries in groups.items():
        lines.append(f"### [{display_name}]({display_name}.md)\n\n")
        for op_key, variant in entries:
            chart = chart_rel_path(arch, dtype, op_key, variant, page_path.parent)
            if chart:
                params = get_params_desc(op_key, variant)
                lines.append(f"![{display_name} {params}]({chart})\n\n")

    return "".join(lines)


def arch_index(arch: str, data_for_arch: dict) -> str:
    """reports/by_arch/{arch}/README.md"""
    lines = [
        f"# {ARCH_DISPLAY.get(arch, arch)}\n",
        GENERATED_NOTE,
        "[← Architectures](../README.md) | [Top](../../README.md)\n\n",
        "## Data Types\n\n",
    ]
    for dtype in DTYPES:
        if dtype in data_for_arch:
            groups = group_by_display(data_for_arch[dtype])
            lines.append(f"- [{DTYPE_DISPLAY.get(dtype, dtype)}]({dtype}/README.md) — {len(groups)} ops\n")

    lines.append("\n## Quick Summary\n\n")
    available_dtypes = [d for d in DTYPES if d in data_for_arch]
    lines.append("| Op | " + " | ".join(
        f"[{DTYPE_DISPLAY.get(d, d)}]({d}/README.md)" for d in available_dtypes
    ) + " |\n")
    lines.append("|----" + "|------" * len(available_dtypes) + "|\n")

    all_display = sorted(set().union(*(
        group_by_display(data_for_arch.get(d, {})).keys() for d in DTYPES
    )))
    for display_name in all_display:
        cells = []
        for dtype in available_dtypes:
            group = group_by_display(data_for_arch.get(dtype, {})).get(display_name)
            if group:
                op_key, variant = group[0]
                summary = load_summary(arch, dtype, op_key, variant)
                if summary:
                    cells.append(f"[{summary['max_ulp']} ULP]({dtype}/{display_name}.md)")
                else:
                    cells.append(f"[data]({dtype}/{display_name}.md)")
            else:
                cells.append("—")
        lines.append(f"| `{display_name}` | " + " | ".join(cells) + " |\n")

    return "".join(lines)


def arch_list_index(data: dict) -> str:
    lines = [
        "# By Architecture\n",
        GENERATED_NOTE,
        "[← Top](../README.md)\n\n",
        "| Architecture | bf16 ops | fp32 ops |\n",
        "|-------------|---------|----------|\n",
    ]
    for arch in sorted(data.keys()):
        bf16_n = len(group_by_display(data[arch].get("bf16", {})))
        fp32_n = len(group_by_display(data[arch].get("fp32", {})))
        lines.append(f"| [{ARCH_DISPLAY.get(arch, arch)}]({arch}/README.md) | {bf16_n} | {fp32_n} |\n")
    return "".join(lines)


def op_cross_arch_page(display_name: str, data: dict) -> str:
    """reports/by_op/{display_name}/README.md — op across all arch/dtype"""
    page_path = REPORTS_DIR / "by_op" / display_name / "README.md"

    # Collect notes/descs from any op_key that maps to this display_name
    all_entries: list[tuple[str, str, str, str]] = []  # (arch, dtype, op_key, variant)
    reg = _get_registry()
    for arch in ARCHS:
        for dtype in DTYPES:
            group = group_by_display(data.get(arch, {}).get(dtype, {})).get(display_name, [])
            for op_key, variant in group:
                all_entries.append((arch, dtype, op_key, variant))

    # Pick a representative op_key for notes/description
    sample_key = all_entries[0][2] if all_entries else display_name
    note = get_op_note(sample_key)
    desc = get_op_description(sample_key)

    lines = [
        f"# `{display_name}` — All Architectures & Data Types\n",
        GENERATED_NOTE,
        "[← All ops](../README.md) | [Top](../../README.md)\n\n",
    ]
    if note:
        lines.append(f"**Valid domain:** {note}  \n")
    if desc:
        lines.append(f"**Notes:** {desc}  \n")
    lines.append("\n")

    if not all_entries:
        lines.append("_No data available yet._\n")
        return "".join(lines)

    # All unique parameter sets across all archs/dtypes
    all_params = sorted(dict.fromkeys(
        get_params_desc(op_key, variant)
        for _, _, op_key, variant in all_entries
    ))

    available_archs  = sorted(dict.fromkeys(a for a, _, _, _ in all_entries))
    available_dtypes = sorted(dict.fromkeys(d for _, d, _, _ in all_entries))

    header = "| Parameters | Arch | " + " | ".join(DTYPE_DISPLAY.get(d, d) for d in available_dtypes) + " |\n"
    sep    = "|------------|------" + "|------" * len(available_dtypes) + "|\n"  # no trailing | before repeat
    lines.extend([header, sep])

    for params in all_params:
        for arch in available_archs:
            cells = []
            for dtype in available_dtypes:
                group = group_by_display(data.get(arch, {}).get(dtype, {})).get(display_name, [])
                entry = next(((k, v) for k, v in group if get_params_desc(k, v) == params), None)
                if entry:
                    op_key, variant = entry
                    summary = load_summary(arch, dtype, op_key, variant)
                    link = f"../../by_arch/{arch}/{dtype}/{display_name}.md"
                    cells.append(f"[{summary['max_ulp']} ULP]({link})" if summary else f"[data]({link})")
                else:
                    cells.append("—")
            arch_label = ARCH_DISPLAY.get(arch, arch)
            lines.append(f"| `{params}` | {arch_label} | " + " | ".join(cells) + " |\n")

    lines.append("\n---\n\n## Charts\n\n")
    for arch in available_archs:
        for dtype in available_dtypes:
            group = group_by_display(data.get(arch, {}).get(dtype, {})).get(display_name, [])
            if not group:
                continue
            lines.append(f"### {ARCH_DISPLAY.get(arch, arch)}, {DTYPE_DISPLAY.get(dtype, dtype)}\n\n")
            for op_key, variant in group:
                params = get_params_desc(op_key, variant)
                chart = chart_rel_path(arch, dtype, op_key, variant, page_path.parent)
                if chart:
                    lines.append(f"**`{params}`**\n\n![{display_name} {params} {arch} {dtype}]({chart})\n\n")

    return "".join(lines)


def op_list_index(data: dict) -> str:
    all_display = sorted(set().union(*(
        group_by_display(data.get(arch, {}).get(dtype, {})).keys()
        for arch in data
        for dtype in DTYPES
    )))

    lines = [
        "# By Operation\n",
        GENERATED_NOTE,
        "[← Top](../README.md)\n\n",
        f"Total: {len(all_display)} ops measured\n\n",
        "| Op | Category | WH bf16 | WH fp32 | BH bf16 | BH fp32 |\n",
        "|----|----------|---------|---------|---------|----------|\n",
    ]

    for display_name in all_display:
        category = "—"
        cells = []
        for arch in ARCHS:
            for dtype in DTYPES:
                group = group_by_display(data.get(arch, {}).get(dtype, {})).get(display_name, [])
                if group:
                    op_key, variant = group[0]
                    if category == "—":
                        category = get_op_category(op_key)
                    summary = load_summary(arch, dtype, op_key, variant)
                    link = f"{display_name}/README.md"
                    cells.append(f"[{summary['max_ulp']}]({link})" if summary else f"[✓]({link})")
                else:
                    cells.append("—")
        lines.append(f"| [{display_name}]({display_name}/README.md) | {category} | " + " | ".join(cells) + " |\n")

    return "".join(lines)


def dtype_index(dtype: str, data: dict) -> str:
    available_archs = sorted(arch for arch in data if dtype in data[arch])
    all_display = sorted(set().union(*(
        group_by_display(data.get(arch, {}).get(dtype, {})).keys()
        for arch in available_archs
    )))

    lines = [
        f"# {DTYPE_DISPLAY.get(dtype, dtype)}\n",
        GENERATED_NOTE,
        "[← Dtypes](../README.md) | [Top](../../README.md)\n\n",
        "| Op | " + " | ".join(ARCH_DISPLAY.get(a, a) for a in available_archs) + " |\n",
        "|----" + "|------" * len(available_archs) + "|\n",
    ]

    for display_name in all_display:
        cells = []
        for arch in available_archs:
            group = group_by_display(data.get(arch, {}).get(dtype, {})).get(display_name, [])
            if group:
                op_key, variant = group[0]
                summary = load_summary(arch, dtype, op_key, variant)
                link = f"../../by_arch/{arch}/{dtype}/{display_name}.md"
                cells.append(f"[{summary['max_ulp']} ULP]({link})" if summary else f"[✓]({link})")
            else:
                cells.append("—")
        lines.append(f"| `{display_name}` | " + " | ".join(cells) + " |\n")

    return "".join(lines)


def dtype_list_index(data: dict) -> str:
    lines = [
        "# By Data Type\n",
        GENERATED_NOTE,
        "[← Top](../README.md)\n\n",
    ]
    for dtype in DTYPES:
        n_wh = len(group_by_display(data.get("wh", {}).get(dtype, {})))
        n_bh = len(group_by_display(data.get("bh", {}).get(dtype, {})))
        lines.append(
            f"- [{DTYPE_DISPLAY.get(dtype, dtype)}]({dtype}/README.md)"
            f" — WH: {n_wh} ops, BH: {n_bh} ops\n"
        )
    return "".join(lines)


def top_readme(data: dict) -> str:
    total_archs = len(data)
    total_ops = len(set().union(*(
        group_by_display(data.get(arch, {}).get(dtype, {})).keys()
        for arch in data
        for dtype in DTYPES
    )))

    lines = [
        "# TT-Metal Eltwise Op Accuracy Reports\n\n",
        GENERATED_NOTE,
        "Accuracy measurements for TT-Metal elementwise operations vs PyTorch golden reference.\n",
        "Charts show ULP (units in last place) error across the full input range.\n\n",
        "---\n\n",
        "## Browse Reports\n\n",
        "| View | Description |\n",
        "|------|-------------|\n",
        "| [By Architecture](by_arch/README.md) | Start from hardware platform (WH, BH), then dtype, then op |\n",
        "| [By Operation](by_op/README.md) | Start from op name, compare across architectures and dtypes |\n",
        "| [By Data Type](by_dtype/README.md) | Start from bf16 or fp32, see all ops on all archs |\n",
        "\n---\n\n",
        "## Quick Stats\n\n",
        "| Metric | Count |\n",
        "|--------|-------|\n",
        f"| Architectures measured | {total_archs} |\n",
        f"| Unique ops measured | {total_ops} |\n",
    ]
    for arch in sorted(data.keys()):
        for dtype in DTYPES:
            n = len(group_by_display(data.get(arch, {}).get(dtype, {})))
            if n:
                lines.append(f"| {ARCH_DISPLAY.get(arch, arch)} {DTYPE_DISPLAY.get(dtype, dtype)} ops | {n} |\n")

    lines.extend([
        "\n---\n\n",
        "## Data Collection\n\n",
        "```bash\n",
        "# Collect measurements (run on target hardware)\n",
        "python scripts/measure_accuracy.py --arch wh --category unary --dtype both\n",
        "\n",
        "# Generate SVG charts and update report_index.json\n",
        "python scripts/generate_charts.py\n",
        "\n",
        "# Regenerate this report tree\n",
        "python scripts/generate_reports.py\n",
        "```\n",
    ])
    return "".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def generate_reports(arch_filter=None, dtype_filter=None, categories=None):
    sys.path.insert(0, str(Path(__file__).parent))
    if categories is None:
        categories = ["unary"]

    data = discover_ops(categories=categories)

    if not data:
        print("No charts found. Run generate_charts.py first.")

    write(REPORTS_DIR / "README.md", top_readme(data))

    write(REPORTS_DIR / "by_arch" / "README.md", arch_list_index(data))
    for arch in (([arch_filter] if arch_filter else sorted(data.keys())) or ARCHS):
        arch_data = data.get(arch, {})
        write(REPORTS_DIR / "by_arch" / arch / "README.md", arch_index(arch, arch_data))
        for dtype in ([dtype_filter] if dtype_filter else DTYPES):
            dtype_ops = arch_data.get(dtype, {})
            write(REPORTS_DIR / "by_arch" / arch / dtype / "README.md",
                  arch_dtype_index(arch, dtype, dtype_ops))
            # One page per display_name (groups multiple op_keys)
            for display_name, entries in group_by_display(dtype_ops).items():
                write(REPORTS_DIR / "by_arch" / arch / dtype / f"{display_name}.md",
                      op_detail_page(arch, dtype, display_name, entries))

    all_display = sorted(set().union(*(
        group_by_display(data.get(arch, {}).get(dtype, {})).keys()
        for arch in data for dtype in DTYPES
    )))
    write(REPORTS_DIR / "by_op" / "README.md", op_list_index(data))
    for display_name in all_display:
        write(REPORTS_DIR / "by_op" / display_name / "README.md",
              op_cross_arch_page(display_name, data))

    write(REPORTS_DIR / "by_dtype" / "README.md", dtype_list_index(data))
    for dtype in ([dtype_filter] if dtype_filter else DTYPES):
        write(REPORTS_DIR / "by_dtype" / dtype / "README.md", dtype_index(dtype, data))

    # Remove stale per-op-key pages that have been merged into display_name pages.
    # A page is stale if its stem is a registry op_key but there's now a separate
    # display_name page for that op's display_name.
    reg = _get_registry()
    for arch in (([arch_filter] if arch_filter else sorted(data.keys())) or ARCHS):
        for dtype in ([dtype_filter] if dtype_filter else DTYPES):
            dtype_dir = REPORTS_DIR / "by_arch" / arch / dtype
            for md in sorted(dtype_dir.glob("*.md")):
                stem = md.stem
                if stem == "README":
                    continue
                if stem in reg and get_display_name(stem) != stem:
                    # This is an old op_key page; the display_name page now covers it
                    md.unlink()
                    print(f"  Removed stale {md.relative_to(REPO_ROOT)}")

    # Remove stale by_op directories for old op_key names
    by_op_dir = REPORTS_DIR / "by_op"
    for op_dir in sorted(by_op_dir.iterdir()):
        if not op_dir.is_dir():
            continue
        stem = op_dir.name
        if stem in reg and get_display_name(stem) != stem:
            import shutil
            shutil.rmtree(op_dir)
            print(f"  Removed stale {op_dir.relative_to(REPO_ROOT)}/")

    print("\nDone.")


def parse_args():
    p = argparse.ArgumentParser(description="Generate markdown report tree")
    p.add_argument("--arch")
    p.add_argument("--dtype")
    p.add_argument("--categories", default="unary",
                   help="Comma-separated categories (default: unary)")
    return p.parse_args()


def main():
    args = parse_args()
    cats = [c.strip() for c in args.categories.split(",")]
    generate_reports(arch_filter=args.arch, dtype_filter=args.dtype, categories=cats)


if __name__ == "__main__":
    main()
